"""Trusted visual theme presets for generated website demos."""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


class ThemeKey(str, Enum):
    """Stable theme identifiers stored by the demo pipeline."""

    GENERAL = "general"
    HAIR_BEAUTY = "hair_beauty"
    AUTOMOTIVE = "automotive"
    PROPERTY = "property"
    LOGISTICS = "logistics"
    EVENT = "event"
    CONSTRUCTION = "construction"


@dataclass(frozen=True, slots=True)
class DemoTheme:
    """A fixed, application-owned visual theme.

    Values are never generated by the model or accepted as arbitrary CSS from
    users. Keeping the palette and visual motif application-owned makes later
    static demo generation deterministic and safe.
    """

    key: ThemeKey
    label: str
    accent: str
    accent_soft: str
    accent_text: str
    background: str
    surface_strong: str
    line: str
    glow: str
    visual_label: str


THEMES: dict[ThemeKey, DemoTheme] = {
    ThemeKey.GENERAL: DemoTheme(
        key=ThemeKey.GENERAL,
        label="Modern Kurumsal",
        accent="#d97706",
        accent_soft="#fff1db",
        accent_text="#8a4a03",
        background="#f6f3ed",
        surface_strong="#111827",
        line="#e6dfd3",
        glow="rgba(217,119,6,.78)",
        visual_label="Modern ve güven veren dijital vitrin",
    ),
    ThemeKey.HAIR_BEAUTY: DemoTheme(
        key=ThemeKey.HAIR_BEAUTY,
        label="Bakım & Stil",
        accent="#a855f7",
        accent_soft="#f6e9ff",
        accent_text="#6b21a8",
        background="#fbf7fc",
        surface_strong="#24152d",
        line="#eadcf0",
        glow="rgba(168,85,247,.72)",
        visual_label="Bakım, stil ve randevu odaklı deneyim",
    ),
    ThemeKey.AUTOMOTIVE: DemoTheme(
        key=ThemeKey.AUTOMOTIVE,
        label="Otomotiv Teknik",
        accent="#2563eb",
        accent_soft="#e8f0ff",
        accent_text="#1e40af",
        background="#f3f6f9",
        surface_strong="#111827",
        line="#d9e0e8",
        glow="rgba(37,99,235,.76)",
        visual_label="Net, teknik ve hızlı iletişim odaklı",
    ),
    ThemeKey.PROPERTY: DemoTheme(
        key=ThemeKey.PROPERTY,
        label="Emlak Premium",
        accent="#0f766e",
        accent_soft="#e3f5f1",
        accent_text="#115e59",
        background="#f5f8f7",
        surface_strong="#16302d",
        line="#d8e5e2",
        glow="rgba(15,118,110,.76)",
        visual_label="Portföy ve güven hissini öne çıkaran",
    ),
    ThemeKey.LOGISTICS: DemoTheme(
        key=ThemeKey.LOGISTICS,
        label="Lojistik Net",
        accent="#ea580c",
        accent_soft="#fff0e5",
        accent_text="#9a3412",
        background="#f8f7f5",
        surface_strong="#292524",
        line="#e7e1dc",
        glow="rgba(234,88,12,.76)",
        visual_label="Hız ve ulaşılabilirliği öne çıkaran",
    ),
    ThemeKey.EVENT: DemoTheme(
        key=ThemeKey.EVENT,
        label="Etkinlik Zarif",
        accent="#be185d",
        accent_soft="#fce7f1",
        accent_text="#9d174d",
        background="#fcf7f9",
        surface_strong="#351624",
        line="#efdce4",
        glow="rgba(190,24,93,.72)",
        visual_label="Etkinlik ve organizasyonlara uygun zarif görünüm",
    ),
    ThemeKey.CONSTRUCTION: DemoTheme(
        key=ThemeKey.CONSTRUCTION,
        label="Yapı Güçlü",
        accent="#b45309",
        accent_soft="#fdf0dc",
        accent_text="#92400e",
        background="#f6f5f2",
        surface_strong="#292524",
        line="#e2ddd5",
        glow="rgba(180,83,9,.78)",
        visual_label="Güçlü, sade ve proje odaklı görünüm",
    ),
}


_THEME_KEYWORDS: tuple[tuple[ThemeKey, tuple[str, ...]], ...] = (
    (
        ThemeKey.HAIR_BEAUTY,
        (
            "kuaför",
            "kuafor",
            "berber",
            "güzellik",
            "guzellik",
            "hair salon",
            "hair_salon",
            "beauty salon",
            "beauty_salon",
        ),
    ),
    (
        ThemeKey.AUTOMOTIVE,
        ("oto", "otomotiv", "servis", "car repair", "car_repair", "auto repair"),
    ),
    (
        ThemeKey.PROPERTY,
        ("emlak", "gayrimenkul", "real estate", "real_estate", "estate agency"),
    ),
    (
        ThemeKey.LOGISTICS,
        ("nakliyat", "taşımacılık", "tasimacilik", "lojistik", "moving", "mover"),
    ),
    (
        ThemeKey.EVENT,
        ("düğün", "dugun", "organizasyon", "event", "wedding", "düğün salonu"),
    ),
    (
        ThemeKey.CONSTRUCTION,
        ("yapı", "yapi", "tadilat", "inşaat", "insaat", "construction", "contractor"),
    ),
)


def recommend_theme(
    sector: str,
    *,
    place_types: tuple[str, ...] = (),
) -> DemoTheme:
    """Recommend a trusted theme from sector text and Google place types."""

    haystack = " ".join((sector, *place_types)).casefold()
    for key, keywords in _THEME_KEYWORDS:
        if any(keyword in haystack for keyword in keywords):
            return THEMES[key]
    return THEMES[ThemeKey.GENERAL]


def resolve_theme(
    theme: ThemeKey | str | None,
    *,
    sector: str,
    place_types: tuple[str, ...] = (),
) -> DemoTheme:
    """Resolve an explicit preset or fall back to a sector recommendation."""

    if theme is None or (isinstance(theme, str) and not theme.strip()):
        return recommend_theme(sector, place_types=place_types)

    try:
        key = theme if isinstance(theme, ThemeKey) else ThemeKey(theme.strip())
    except ValueError as exc:
        raise ValueError(f"Unknown demo theme: {theme!r}") from exc
    return THEMES[key]


def render_theme_css(theme: DemoTheme) -> str:
    """Render CSS overrides from an application-owned preset only."""

    return f"""
:root {{
  --bg: {theme.background};
  --surface-strong: {theme.surface_strong};
  --line: {theme.line};
  --accent: {theme.accent};
  --accent-soft: {theme.accent_soft};
}}
.eyebrow {{ color: {theme.accent_text}; }}
.hero-panel::after {{
  background: radial-gradient(circle, {theme.glow}, rgba(0,0,0,0));
}}
.about-visual {{
  background:
    linear-gradient(145deg, {theme.surface_strong}, {theme.surface_strong}e6),
    radial-gradient(circle at 25% 20%, {theme.glow}, transparent 38%);
}}
.contact-shell .section-kicker,
.location-link {{ color: {theme.accent}; }}
""".strip()
